program: main.py
method: bayes  # bayes è meglio di random/grid per spazi continui

metric:
  name: val/dice
  goal: maximize

parameters:
  # Iperparametri da cercare
  lr:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-3

  batch_size:
    values: [1, 2, 4]

  loss:
    values: [DiceCELoss, TwerskyLoss]

  epochs:
    value: 100  # fisso durante lo sweep

  # Fissi — non variano nello sweep
  model:
    value: MAE_2Channel
  image_size:
    value: 512  # usa 512 durante lo sweep per velocità
  device:
    value: cuda:0
  zarr_path:
    value: /home/gpatane/Dataset/zarr_file_magnetogram_1024_definitivo.zarr
  mae_checkpoint:
    value: /home/gpatane/checkpoints/mae_ckp/best_model.pth
  model_path:
    value: /home/gpatane/checkpoints/sweep/